/* ------------------------------------------------------------------
   Day One — the presentations.

   Same system as lib/decks.js: slides are data, they render through
   components/deck.jsx and components/deck-art.jsx, and nobody has to
   open Keynote to fix a typo. The slide kinds, their props and the
   editorial constraints are all documented in lib/decks.js — read that
   header before adding a slide here.

   The two rules worth repeating, because they're the ones that get
   broken: no more than two consecutive text-only slides, and at least
   three diagram slides per fifteen. Terminals count as neither — they
   break a text run without being a diagram.

   Program-specific notes:
     · Dates are TBD. No slide states or implies one, including the end
       slides — a session is referred to by its number, never a date.
     · The timeline slide sits in position four of every deck and takes
       no data beyond its note; the renderer draws the program's own
       session spine.
     · QR keys are `day-one-<session-slug>`, generated by
       scripts/build-kits.mjs alongside the Zero to Launch ones.
------------------------------------------------------------------ */

export const DAY_ONE_DECKS = {
  "first-threads": [
    { kind: "title", sub: "Getting real work out of ChatGPT and Claude" },
    {
      kind: "statement",
      text: "The blank box is the whole problem.",
      note: "Everyone in this room already has an account. Almost nobody has a thread that ended in something they kept.",
    },
    {
      kind: "agenda",
      title: "Tonight",
      items: [
        "Pick the business — one, and it's yours",
        "The anatomy of a thread that produces something",
        "Chat as search versus chat as work",
        "Skills: teach it once, stop re-explaining",
        "Your brand voice, built on screen",
        "Your ICP, built on screen",
        "The one-pager, and the first article drafted",
      ],
    },

    {
      kind: "timeline",
      title: "Where we are",
      note: "Four sessions, one business — yours. Every session is free and standalone, each one leaves a folder the next one reads, and catching up late is explicitly allowed.",
    },

    {
      kind: "act",
      n: "01",
      eyebrow: "Act one",
      title: "The thread",
      c: "Most people are running a search engine that types slowly. Five things separate that from a thread that hands you work.",
    },
    {
      kind: "flow",
      title: "What a good thread actually contains",
      steps: [
        { t: "Context", c: "What you're working on, who it's for, what already exists. Paste the real thing, not a description of it." },
        { t: "Role", c: "Who it should be while it answers. \"Someone who has read our last four emails\" beats \"an expert\"." },
        { t: "Task", c: "One job, stated as a verb. If it has an \"and\" in it, that's two threads." },
        { t: "Format", c: "How you want it back — length, structure, the shape you'll actually use." },
        { t: "Artifact", c: "The file you keep. Everything above this step is setup for this one.", lit: true },
      ],
      note: "Nobody writes this in order the first time. You write the task, get something generic back, and add the other four.",
    },
    {
      kind: "split",
      title: "Two ways to use the same box",
      left: {
        h: "Chat as search",
        items: [
          "One question at a time",
          "Answers you skim",
          "Starts from zero every time",
          "Output lives in the scrollback",
          "You get faster at typing",
        ],
      },
      right: {
        h: "Chat as work",
        items: [
          "A brief, then a draft",
          "Work you edit and send",
          "Starts from your own material",
          "Output lands in a file",
          "Tomorrow starts where tonight ended",
        ],
      },
      note: "Same box, same model. The difference is whether anything survives the tab closing.",
    },
    {
      kind: "statement",
      text: "Every good thread ends in an artifact you keep.",
      note: "A file, a page, a draft. If tonight only made you feel productive, it didn't happen.",
    },

    {
      kind: "act",
      n: "02",
      eyebrow: "Act two",
      title: "Skills",
      c: "The third time you explain your business to a model, you're doing unpaid data entry. A skill is that explanation, written once, read automatically from then on.",
    },
    {
      kind: "loop",
      title: "The skill loop",
      label: "compounds",
      steps: [
        { t: "You explain the same thing for the third time" },
        { t: "That explanation becomes a skill file" },
        { t: "Every thread after it starts there" },
        { t: "You tune it on whatever sounded wrong" },
      ],
      note: "It's markdown with a bit of frontmatter. No framework, no platform — a folder your agent reads before it answers you.",
    },
    {
      kind: "terminal",
      cmd: "/skill-writer",
      out: ["what do you re-explain every time?", "drafting frontmatter + steps…", "wrote .claude/skills/brand-voice/SKILL.md"],
      title: "Teach it once",
      c: "It asks what you keep repeating, takes real examples rather than adjectives, writes the steps as instructions, then tests the result in a fresh thread — because a skill that only works in the thread that wrote it isn't a skill.",
      note: "The first one everybody should write is voice. Feed it three things you actually wrote and let /brand-voice pull the do/don't pairs out of your own sentences.",
    },
    {
      kind: "terminal",
      cmd: "/icp-profile",
      out: ["who pays, and what just happened to them", "1 disqualifier written down", "wrote 01-voice/icp.md"],
      title: "Who it's for, in writing",
      c: "Three answers: who pays, the trigger that makes this urgent now instead of someday, and the disqualifier. The disqualifier is the one everyone skips and the one that makes every later draft specific.",
      note: "Written as a skill, not a note — so the calendar, the outbound and the support agent all read the same definition instead of three different guesses.",
    },

    {
      kind: "act",
      n: "03",
      eyebrow: "Act three",
      title: "Point it at your business",
      c: "One business, picked tonight, carried through all four sessions. Not a demo project — the thing you'd actually like customers for.",
    },
    {
      kind: "matrix",
      title: "One business, four sessions",
      heads: ["Tonight", "Where it goes"],
      rows: [
        { t: "Voice", cells: ["A skill built from your own writing", { v: "Every draft, page and reply after this", lit: true }] },
        { t: "ICP", cells: ["Who pays, the trigger, the disqualifier", { v: "The calendar, the outbound, the agent", lit: true }] },
        { t: "Positioning", cells: ["One page you'd defend to a stranger", { v: "The hero of the site you ship in 03", lit: true }] },
        { t: "The draft", cells: ["One article, claims marked", { v: "The pipeline that drafts them in 04", lit: true }] },
      ],
      note: "Nothing tonight is a warm-up exercise. Every file in the left column is an input to a session that comes after it.",
    },
    {
      kind: "terminal",
      cmd: "/positioning-brief  →  /article-draft",
      out: ["reading brand-voice + 01-voice/icp.md", "one-liner failed the swap test — retrying", "wrote positioning.md, article-01.md"],
      title: "The one-pager, then the first draft",
      c: "The brief compresses everything above into one line, then applies the swap test: put a competitor's name in it, and if it still reads true it isn't positioning. The article comes out in your voice because the voice is a file it can read.",
      note: "Drafted tonight, published when the claims check out. Every number in it gets marked verified or unverified before it goes anywhere.",
    },
    { kind: "quote", text: "Demos over memos." },
    {
      kind: "end",
      next: "Daily Driver — Session 02, Workuity Biltmore",
      qr: "day-one-coworking-with-ai",
      qrLabel: "Session page",
      c: "Tonight everything happened because you asked. Next session it happens on a schedule — a live content calendar, a weekly report that has already run once, and outbound drafted for you to send.",
    },
  ],

  "coworking-with-ai": [
    { kind: "title", sub: "Routines, artifacts, and work that runs on a schedule" },
    {
      kind: "statement",
      text: "AI that waits to be asked is a tool. AI on a calendar is a coworker.",
      note: "Tonight is the difference between those two, built on screen with your files from session 01.",
    },
    {
      kind: "agenda",
      title: "Tonight",
      items: [
        "What a routine is — skill, trigger, checkpoint",
        "Artifacts versus live artifacts",
        "A four-week content calendar, built on screen",
        "Scheduled tasks, demoed live",
        "The weekly report that runs without you",
        "Outbound, drafted — never sent",
        "The checkpoint rule",
      ],
    },

    {
      kind: "timeline",
      title: "Where we are",
      note: "Four sessions, one business — yours. Every session is free and standalone, each one leaves a folder the next one reads, and catching up late is explicitly allowed.",
    },

    {
      kind: "act",
      n: "01",
      eyebrow: "Act one",
      title: "Artifacts",
      c: "A routine is three things: a skill that knows how, a trigger that fires it, and a checkpoint where you're still in the loop. All three start with something worth reading.",
    },
    {
      kind: "split",
      title: "Dead artifact, live artifact",
      left: {
        h: "Dead",
        items: [
          "Generated once, perfect that day",
          "Regenerated from scratch when stale",
          "Lives in a chat you closed",
          "Nobody adds to it",
          "Rewritten every month",
        ],
      },
      right: {
        h: "Live",
        items: [
          "Generated once, then edited forever",
          "Updated when something changes",
          "Lives in a file in your repo",
          "Every routine reads it",
          "More useful in month three",
        ],
      },
      note: "The tell is simple: if the fix for a stale file is \"regenerate it\", it was never live.",
    },
    {
      kind: "terminal",
      cmd: "/content-calendar",
      out: ["reading 01-voice/icp.md", "4 weeks, 12 pieces, from real questions", "wrote 02-routines/calendar.md"],
      title: "Four weeks, from what they actually ask",
      c: "Not topics that sound like marketing. The questions your ICP types into a search box, and the ones they ask you on a call — turned into a dated four weeks you can argue with.",
      note: "The moment it exists, add one thing to it by hand. That's the edit that makes it yours instead of output.",
    },

    {
      kind: "act",
      n: "02",
      eyebrow: "Act two",
      title: "Schedules",
      c: "Every assistant worth using now runs work on a clock — tasks in ChatGPT, scheduled tasks in Claude, cron if you'd rather own it. The mechanism is the boring part. The pattern is the same everywhere.",
    },
    {
      kind: "flow",
      title: "What a routine is made of",
      steps: [
        { t: "The schedule", c: "Monday at seven, every week, whether you remembered or not." },
        { t: "The skill", c: "The instructions you already wrote once, run again unchanged." },
        { t: "The draft", c: "It reads your files first, then writes. Same inputs you'd have given it by hand." },
        { t: "The checkpoint", c: "You read it. Genuinely, or not at all.", lit: true },
        { t: "The file", c: "It lands somewhere you'll find it later, not in a chat window you closed." },
      ],
      note: "A checkpoint you never actually read isn't a checkpoint — it's theatre with your name on it. Remove it or mean it.",
    },
    {
      kind: "terminal",
      cmd: "/weekly-report",
      out: ["5 numbers you can actually get", "scheduled: Mondays, 7:00 AM", "first run landed — 168 words"],
      title: "The report that shows up on its own",
      c: "Three to five numbers you can genuinely obtain, under two hundred words, in plain English. It says what moved and what it thinks that means, and it's honest about small numbers instead of dressing them up as percentages.",
      note: "If it hasn't run once, it isn't set up. Watch the first one land before you trust the second.",
    },

    {
      kind: "act",
      n: "03",
      eyebrow: "Act three",
      title: "Outbound, drafted",
      c: "The most useful thing an agent does for outbound is the ninety percent before the send button. The send button stays yours.",
    },
    {
      kind: "matrix",
      title: "Who does what",
      heads: ["The agent", "You"],
      rows: [
        { t: "The list", cells: ["Twenty named accounts, each with a reason", { v: "Cut the ones that don't fit", lit: true }] },
        { t: "The sequence", cells: ["First touch, two follow-ups, a break-up", { v: "Cut anything you wouldn't reply to", lit: true }] },
        { t: "The specifics", cells: ["One line per account that couldn't be in anyone else's", { v: "Check that it's true", lit: true }] },
        { t: "Sending", cells: ["Never", { v: "Every one of them, by hand", lit: true }] },
      ],
      note: "Twenty relevant emails take an afternoon. Five hundred bad ones take an afternoon too, and cost you the domain.",
    },
    {
      kind: "terminal",
      cmd: "/icp-builder  →  /outbound-sequence",
      out: ["20 named accounts, 6 filtered out", "1 touch + 2 follow-ups, drafted", "wrote 02-routines/outbound/ — 0 sent"],
      title: "Drafts, into a folder",
      c: "The ICP profile from session 01 becomes a named list, then a sequence short enough to read on a phone. It writes to a folder and stops there — nothing in this program has your outbox.",
    },
    {
      kind: "loop",
      title: "The week, on rails",
      label: "every week",
      steps: [
        { t: "Monday: the numbers land before you open the laptop" },
        { t: "The calendar says what this week's piece is" },
        { t: "Drafts show up in the folder, in your voice" },
        { t: "You edit, you send, and the calendar gets updated" },
      ],
      note: "None of this is new work. It's the same work, minus the remembering — and the last step is the one that keeps the whole loop honest.",
    },
    { kind: "quote", text: "Proof of work." },
    {
      kind: "end",
      next: "First Deploy — Session 03, Workuity Biltmore",
      qr: "day-one-first-deploy",
      qrLabel: "Session page",
      c: "Everything so far lives in a chat window and a folder. Next session it gets a URL. Bring Node, a GitHub account and a Vercel account — the setup instructions go out in Discord beforehand, and we do the install together in the room.",
    },
  ],

  "first-deploy": [
    { kind: "title", sub: "A marketing site, built and deployed in one sitting" },
    {
      kind: "statement",
      text: "Everything so far has lived in a chat window. Tonight it gets a URL.",
      note: "Same business, same files, same voice. A stranger can finally read it.",
    },
    {
      kind: "agenda",
      title: "Tonight",
      items: [
        "The chat, in your files",
        "Setup, together — the slowest fifteen minutes we run",
        "Your one-pager becomes the hero",
        "Structure: one CTA, proof over adjectives",
        "Pages at scale, without the spam",
        "The articles get a home",
        "Deploy — a real URL, tonight",
      ],
    },

    {
      kind: "timeline",
      title: "Where we are",
      note: "Four sessions, one business — yours. Every session is free and standalone, each one leaves a folder the next one reads, and catching up late is explicitly allowed.",
    },

    {
      kind: "act",
      n: "01",
      eyebrow: "Act one",
      title: "The chat, in your files",
      c: "Claude Code and Codex are the same model you've been talking to for two sessions. The difference is that they can open your files, run the build, and read the error themselves.",
    },
    {
      kind: "split",
      title: "The jump",
      left: {
        h: "The chat window",
        items: [
          "You paste the code in",
          "You paste the answer back",
          "It can't see the other forty files",
          "Every session starts blank",
          "You are the copy-paste layer",
        ],
      },
      right: {
        h: "The agent in your repo",
        items: [
          "It reads the project itself",
          "It writes the file",
          "It runs the build and sees the error",
          "It remembers what's in here",
          "You review and decide",
        ],
      },
      note: "It's a terminal, which is the part that puts people off. Nothing tonight needs you to memorise a single command.",
    },
    {
      kind: "terminal",
      cwd: "~/",
      cmd: "npm i -g @anthropic-ai/claude-code  &&  claude",
      out: ["node v22 — ok", "logged in", "ready in ~/day-one"],
      title: "Setup, together",
      c: "The slowest fifteen minutes in the program, and we spend them as a room: Node, an account, an agent that starts, the template cloned. Nobody moves on while the person next to them is still installing.",
      note: "Instructions went out in Discord before tonight, and this session needs a paid plan or an API key — said plainly rather than discovered halfway through. If you did the setup at home, this is your coffee break.",
    },

    {
      kind: "act",
      n: "02",
      eyebrow: "Act two",
      title: "The site",
      c: "Every section has a job. Anything without one gets cut, however nice it looks — and the hero is a test of session 01, not a writing exercise.",
    },
    {
      kind: "flow",
      title: "Top to bottom",
      steps: [
        { t: "Hero", c: "What it is, who it's for, one thing to do next. Your one-pager, unchanged if it was any good.", lit: true },
        { t: "Proof", c: "Immediately after. A number, the product doing the hard case, one sentence a real person said." },
        { t: "How it works", c: "Three steps. If it needs five, the product is explaining itself badly." },
        { t: "The objection", c: "Name what they're worried about before they leave to go worry about it." },
        { t: "One CTA", c: "The same one, repeated. A second call to action is the same as none." },
      ],
      note: "If the positioning doesn't survive contact with the page, the positioning was the problem — not the page.",
    },
    {
      kind: "terminal",
      cmd: "/site-scaffold  →  /landing-copy  →  /og-image",
      out: ["scaffolding app/ …", "hero ← 01-voice/positioning.md", "preview: your-site.vercel.app"],
      title: "Scaffold, then say something",
      c: "Routing, metadata and sections first, because an empty page you can deploy beats a perfect page you can't. Then the copy, pulled from the one-pager you wrote in session 01. Then links that preview properly, which is ten minutes you spend once.",
      note: "Proof over adjectives, all the way down. \"Blazing fast\" is discounted by every stranger who reads it; a number with a method behind it isn't.",
    },

    {
      kind: "act",
      n: "03",
      eyebrow: "Act three",
      title: "Pages at scale",
      c: "One table of real data and one template becomes a page per row. Done carelessly it's spam. Done once, carefully, it's the cheapest traffic you'll ever build.",
    },
    {
      kind: "prism",
      title: "One dataset, many pages",
      note: "The same rows, refracted into whichever shape someone actually searches for. Your ICP file already says what they're looking for — this is that list, turned into pages that answer one query each.",
      channels: ["Comparisons", "Use cases", "Integrations", "Locations"],
      rays: 4,
    },
    {
      kind: "bullets",
      title: "The line between scale and spam",
      items: [
        { t: "The doorway test", c: "Read one generated page out loud. If it's a keyword with a header on it, that's a doorway page — search engines are explicitly built to bin those." },
        { t: "Sample of five", c: "Generate five before you generate five hundred. Five is enough to see whether the template has anything to say." },
        { t: "Templated where the data is real", c: "Rows that genuinely differ get a template. Anything that needs judgement gets written by a human, or doesn't get written." },
      ],
      note: "The test isn't \"would this rank\". It's \"would a person be glad they landed here\".",
    },
    {
      kind: "terminal",
      cmd: "/content-map  →  /programmatic-pages  →  deploy",
      out: ["18 real queries → 12 pages", "generating 5 as a sample…", "deployed — live in 34s"],
      title: "Tonight's run",
      c: "Work backwards from what your ICP types into a search box, generate five pages from real data, read one of them properly, then push. The articles you drafted in session 01 get a home on the same deploy.",
    },
    {
      kind: "bignum",
      label: "Your site",
      v: "Live",
      delta: "tonight",
      c: "Not staged, not on your laptop. A URL you can paste into a message and watch someone open.",
    },
    { kind: "quote", text: "If it ships, it speaks." },
    {
      kind: "end",
      next: "The Night Shift — Session 04, Workuity Biltmore",
      qr: "day-one-agentic-workflows",
      qrLabel: "Session page",
      c: "The site you just shipped grows a support agent that answers from your own pages, and a workflow that drafts next week's article while you sleep. Same repo, prepared branch, nothing built from scratch.",
    },
  ],

  "agentic-workflows": [
    { kind: "title", sub: "A support agent and a workflow that runs while you sleep" },
    {
      kind: "statement",
      text: "Until tonight, everything waited for you to show up.",
      note: "The skills, the site, the drafts — all of it starts when you open a laptop. Tonight two things stop waiting.",
    },
    {
      kind: "agenda",
      title: "Tonight",
      items: [
        "Agent versus workflow — and when each one is wrong",
        "The handoff: your session 03 repo, on a branch",
        "The support agent, on your own site",
        "Guardrails, written before it goes live",
        "The night shift — pick one workflow",
        "Watch a run, then break one on purpose",
        "What compounds from here",
      ],
    },

    {
      kind: "timeline",
      title: "Where we are",
      note: "Four sessions, one business — yours. Every session is free and standalone, each one leaves a folder the next one reads, and catching up late is explicitly allowed.",
    },

    {
      kind: "act",
      n: "01",
      eyebrow: "Act one",
      title: "Agent vs workflow",
      c: "Two different shapes with two different failure modes. Naming which one you're building decides how you test it.",
    },
    {
      kind: "matrix",
      title: "Two shapes",
      heads: ["Agent", "Workflow"],
      rows: [
        { t: "Trigger", cells: ["Someone asks", "The clock"] },
        { t: "Shape", cells: ["A conversation, one turn at a time", "Fixed steps, start to finish"] },
        { t: "Fails by", cells: ["Answering confidently and wrong", "Failing silently at three in the morning"] },
        { t: "You test it by", cells: ["Asking it ten real questions", "Running it by hand and reading the logs"] },
        { t: "Tonight", cells: [{ v: "Support, on your own site", lit: true }, { v: "Drafts, into a review queue", lit: true }] },
      ],
      note: "Neither of these is smarter than the other. One is a front door and one is a factory.",
    },
    {
      kind: "terminal",
      cwd: "~/day-one-site",
      cmd: "git fetch  &&  git switch night-shift",
      out: ["app/api/chat/route.ts — new", "workflows/weekly.ts — new", "2 packages added"],
      title: "The handoff",
      c: "Tonight extends the exact repo you shipped in session 03 — no fresh codebase, no second setup night. The branch brings an empty chat route and an empty workflow. You write what goes in them; the plumbing is already wired.",
      note: "The branch is pre-tested. If yours doesn't start, we fix it in the room rather than at the end.",
    },

    {
      kind: "act",
      n: "02",
      eyebrow: "Act two",
      title: "The support agent",
      c: "A chat box on your site that answers from your own content, and knows the difference between a question it can answer and one it shouldn't touch.",
    },
    {
      kind: "flow",
      title: "What happens when a stranger asks",
      steps: [
        { t: "Message", c: "Someone asks something on your site, at whatever hour they're awake." },
        { t: "Classify", c: "Is this in your content, out of scope, or something only a human should touch?" },
        { t: "Answer", c: "From your own pages, with the page it came from attached." },
        { t: "Escalate", c: "\"I don't know — here's a human.\" A valid outcome, and the one that keeps it honest.", lit: true },
        { t: "Log", c: "Every conversation written down. Next month's FAQ is already in there." },
      ],
      note: "The third outcome is refuse: pricing negotiations, promises, anything with your signature on it. It says no and hands over.",
    },
    {
      kind: "bullets",
      title: "Guardrails, written first",
      items: [
        { t: "Never promise", c: "No delivery dates, no refunds, no \"we can definitely do that\". An agent that commits on your behalf has written you a contract." },
        { t: "Never negotiate price", c: "It can quote what's published. Anything past that is a human conversation." },
        { t: "Never send email", c: "It drafts and hands over. Same rule as session 02 — sending is yours." },
        { t: "\"I don't know\" is allowed", c: "Written into the prompt as a valid answer, with the human it hands to. Confident and wrong costs more than slow." },
      ],
      note: "This file gets written before you deploy, not after the first screenshot of it going wrong.",
    },
    {
      kind: "terminal",
      cmd: "/support-agent",
      out: ["answers from your pages, not model memory", "3 outcomes: answer · escalate · refuse", "wrote 04-agents/guardrails.md"],
      title: "Build it, then try to break it",
      c: "The prompt is built from the site you already shipped, so it cites your content instead of remembering something plausible about your industry. Then ten real questions, two of which it has no business answering.",
      note: "If it answers both of those two, it isn't ready. That's the test, and it takes five minutes.",
    },

    {
      kind: "act",
      n: "03",
      eyebrow: "Act three",
      title: "The night shift",
      c: "One workflow, running on a schedule, doing the part of your week that never needed you. Pick one tonight — the other one is a step in the guide.",
    },
    {
      kind: "loop",
      title: "The article path",
      label: "runs weekly",
      steps: [
        { t: "The calendar names this week's piece" },
        { t: "The agent drafts it in your voice" },
        { t: "Claims come back marked verified or unverified" },
        { t: "It lands in a review queue — never on the site" },
      ],
      note: "Nothing publishes itself. The queue is the checkpoint from session 02, wearing a different hat — and the numbers path is the same loop with your report at the end of it.",
    },
    {
      kind: "terminal",
      cmd: "/scheduled-workflow",
      out: ["manual trigger first — run #1 in 4.2s", "logs read, one failure forced", "schedule enabled: Mondays 06:00"],
      title: "Manual first, always",
      c: "Run it by hand, read the logs, then turn the schedule on. Then break it on purpose and confirm you hear about it — a cron job that fails silently is worse than no cron job, because you'll trust it for a month.",
    },
    {
      kind: "scorecard",
      title: "What runs without you now",
      rows: [
        { t: "Answers a repeat question", pct: 90 },
        { t: "Drafts the week's article", pct: 80 },
        { t: "Reports the numbers", pct: 100, lit: true },
        { t: "Decides what ships", pct: 0 },
      ],
      note: "Four sessions ago this was a blank box in a chat window. The bottom row is zero on purpose, and it's the one you keep.",
    },
    { kind: "quote", text: "Feel the fear and do it anyways." },
    {
      kind: "end",
      next: "Zero to Launch — the ten-week program",
      qr: "day-one-agentic-workflows",
      qrLabel: "Tonight's kit",
      c: "Day One got it running. Zero to Launch is the one that puts customers in front of it — funnel, positioning, distribution, and a hackathon at the end where you ship it in public. Tonight's deck, guide and skill files are on the session page.",
    },
  ],
};
