/* ------------------------------------------------------------------
   Day Zero — the presentations.

   Same system as lib/decks.js: slides are data, they render through
   components/deck.jsx and components/deck-art.jsx, and nobody has to
   open Keynote to fix a typo. The slide kinds, their props and the
   editorial constraints are all documented in lib/decks.js — read that
   header before adding a slide here.

   The two rules worth repeating, because they're the ones that get
   broken: no more than two consecutive text-only slides, and at least
   three diagram slides per fifteen. Terminals count as neither — they
   break a text run without being a diagram.

   Program-specific notes:
     · Dates live in lib/dayzero.js and reach the deck through the
       renderer — no slide hard-codes one. Sessions without a date yet
       are referred to by their number.
     · Session 01 is a full live-night deck (about/sponsors/brief/break,
       same skeleton as gtm-engineering in lib/decks.js); the timeline
       slide follows the opening block. Sessions 02–04 keep the shorter
       talk-only shape with the timeline at position four.
     · QR keys are `day-zero-<session-slug>`, generated by
       scripts/build-kits.mjs alongside the Zero to Launch ones.
------------------------------------------------------------------ */

import { ABOUT_SLIDE, HOST_SLIDE } from "./deck-shared.js";

/* The session mark — ANSI-shadow block letters, same face as the
   Zero to Launch decks. Letters are fixed-width cells joined with one
   space (two between words), so the pre stays rectangular. */
const ASCII_DAY0 = `██████╗   █████╗  ██╗   ██╗   ██████╗
██╔══██╗ ██╔══██╗ ╚██╗ ██╔╝  ██╔═████╗
██║  ██║ ███████║  ╚████╔╝   ██║██╔██║
██║  ██║ ██╔══██║   ╚██╔╝    ████╔╝██║
██████╔╝ ██║  ██║    ██║     ╚██████╔╝
╚═════╝  ╚═╝  ╚═╝    ╚═╝      ╚═════╝ `;

export const DAY_ZERO_DECKS = {
  "first-threads": [
    { kind: "title", ascii: ASCII_DAY0, sub: "Skills, agents, and a sneak peek at Grok Bot" },
    {
      kind: "agenda",
      title: "Tonight",
      items: [
        "The brief — thirty minutes of AI news worth arguing about",
        "Break — five minutes, timed by the slide",
        { t: "Skills and agents — from a markdown file to something that runs", lit: true },
        "Live demos — a thread, a skill, a sneak peek at Grok Bot",
        "What's next — and who made tonight happen",
      ],
    },
    ABOUT_SLIDE,
    {
      kind: "bullets",
      cols: 2,
      title: "How the room works",
      items: [
        { t: "Free and open", c: "No tickets, no tiers, no gatekeeping. You pay by teaching what you know back to the room." },
        { t: "Demos over memos", c: "Show the build. Founders too — demo the product, skip the hard sell. If it ships, it speaks." },
        { t: "Craft over hype", c: "The toolchain, the tradeoffs, the parts that hurt." },
        { t: "Honest starting points", c: "Say where you actually are. Nothing solid gets built on an inflated baseline." },
        { t: "Proof of work", c: "A small real result beats a big vague claim. Receipts over adjectives." },
        { t: "Community-driven", c: "Every session ends in five-minute demos, and what you're stuck on shapes the next one." },
      ],
    },
    {
      kind: "split",
      title: "Come as you are, if you build",
      left: {
        h: "Maybe not yet if",
        items: [
          "You're here to hard-sell or fill a lead list",
          "\"AI-powered\" is the whole pitch, with no build behind it",
        ],
      },
      right: {
        h: "This is for you if",
        items: [
          "The chat box is the only AI you've used — that's tonight's starting line",
          "You'll follow along on a laptop, or just watch",
          "You'd rather watch a real demo, even one that breaks, than a canned pitch",
          "You want a room that argues about tradeoffs, not definitions",
        ],
      },
      note: "This is session one of four. Every night stands alone; the files compound if you come back.",
    },
    HOST_SLIDE,
    {
      kind: "end",
      eyebrow: "Before we start",
      next: "Join the Ship AI Discord",
      qrLabel: "discord.gg/kZSJMNveYM",
      c: "Everything from tonight lands there — the deck, the skills, the demos, the arguments we don't finish. Free, always.",
    },
    {
      kind: "sponsors",
      title: "Community partners",
      orgs: [
        { name: "Workuity", img: "/sponsor-workuity.png", tag: "Platinum sponsor · Venue" },
        { name: "CEI Gateway", img: "/sponsor-cei.png", tag: "Community partner" },
        { name: "Venture Café Phoenix", img: "/sponsor-venturecafe.png", tag: "Community", wide: true },
      ],
      note: "The rooms, the nights, the coffee. Ship AI is free because these three show up for builders.",
    },
    {
      kind: "sponsors",
      title: "Current sponsors",
      orgs: [
        { name: "desic", img: "/sponsor-desic.svg", tag: "Gold · AI deployment" },
        { name: "AutomationInterns.com", img: "/sponsor-automationinterns.png", tag: "Gold · Everyday AI", color: true },
      ],
    },
    {
      kind: "end",
      eyebrow: "Sponsors",
      next: "Ship AI is seeking corporate sponsors",
      qr: "sponsors",
      qrLabel: "The menu — shipai.club",
      c: "Free for the room means funded by somebody. Published tiers run $1,000 to $10,000 — cash, credits, or hours all count — and we're flexible: there's opportunity at every price point, and a custom arrangement is always on the table.",
    },

    {
      kind: "timeline",
      title: "Where we are",
      note: "Four sessions, one business — yours. Every session is free and standalone, each one leaves a folder the next one reads, and catching up late is explicitly allowed.",
    },

    /* ---- segment one: the brief ---- */
    {
      kind: "act",
      n: "01",
      eyebrow: "Segment one",
      title: "The brief",
      art: "net",
      c: "Five stories from the last week, plus quick hits. Thirty minutes of the loudest room in AI — then we write a skill and watch it run.",
    },
    {
      kind: "news",
      n: "01",
      title: "Stripe to buy OpenRouter for $7B+",
      src: "@TechCrunch · Aug 16",
      href: "https://x.com/TechCrunch/status/2089094629467513231",
      facts: [
        "Bloomberg: Stripe finalized a deal above $7B. Stripe declined to comment.",
        "OpenRouter's May Series B: $113M at $1.3B. Sequoia, a16z, Menlo, CapitalG.",
        "One API to 400+ models. OpenRouter claimed 8 million users. The CEO's line was \"Stripe for AI.\"",
      ],
      prompt: "The router just got bought by the payments company. Do you keep routing through it?",
    },
    {
      kind: "news",
      n: "02",
      title: "Anthropic shows a profitable quarter",
      src: "Bloomberg · Aug 14",
      href: "https://thenextweb.com/news/anthropic-q2-2026-revenue-11-5-billion-operating-income",
      facts: [
        "Q2 revenue passed $11.5B — more than 14x the $787M a year earlier. Q1 was $4.73B.",
        "First frontier lab to put positive adjusted operating income in front of investors.",
        "Preliminary, unaudited. Anthropic declined to comment. An autumn IPO is the point of the disclosure.",
      ],
      prompt: "If the lab is already profitable, does your API bill go up from here, or down?",
    },
    {
      kind: "news",
      n: "03",
      title: "Qwen 27B runs on a laptop",
      src: "@Alibaba_Qwen · Aug 14",
      href: "https://x.com/Alibaba_Qwen/status/2088280182356611304",
      facts: [
        "Qwen3.8-27B: dense, multimodal, Apache 2.0. 262K native context, 1M via YaRN. Officially beats Qwen3.7-Plus overall.",
        "LM Studio: about 17GB to run locally.",
        "Cline, Aug 17: Artificial Analysis puts it with DeepSeek V4-Pro and GPT-5.6 Luna — \"the first time a local model has scored frontier model capability.\"",
      ],
      prompt: "If a 17-gig local model sits next to Luna, what is the cloud API still for?",
    },
    {
      kind: "news",
      n: "04",
      title: "Gemini 3.7 Flash, three weeks later",
      src: "@GoogleDeepMind · Aug 13",
      href: "https://x.com/GoogleDeepMind/status/2087948366294515977",
      facts: [
        "Shipped Aug 13, three weeks after 3.6 Flash. Live in the API, AI Studio, Antigravity, and Android Studio.",
        "Intro price: $0.75 / $3.75 per 1M tokens through Dec 31. Then $1.50 / $7.50.",
        "Coding vs 3.6: FrontierCode 43.6% vs 34.4%. DeepSWE 65.3% vs 49.0%.",
      ],
      prompt: "A new Flash every three weeks. Do you keep switching, or freeze a model and ignore the rest?",
    },
    {
      kind: "news",
      n: "05",
      title: "Nvidia underwrites OpenAI's Ohio factory",
      src: "@JensenHuang · Aug 17",
      href: "https://x.com/JensenHuang/status/2089331487342829862",
      facts: [
        "PORTS-Pike, Pike County, Ohio. OpenAI is the tenant on a 20-year lease. Nvidia is the exclusive compute. Phases start in 2028.",
        "Initial 4.25 gigawatts. Each generation at the site: about 1.5 million GPUs, $150–200B of Nvidia revenue.",
        "Jensen's number for OpenAI's Nvidia compute through 2030: roughly $600B, with an option to go from 12 GW to 16.",
      ],
      prompt: "Nvidia is guaranteeing the building its biggest customer rents. Who is actually taking the risk?",
    },
    {
      kind: "bullets",
      title: "Quick hits",
      items: [
        { t: "GLM-5.3 is post-training only", c: "Same 743B base as 5.2. Z.ai says 2,436 vulns across 269 projects. Weights in two weeks, after a safety pass." },
        { t: "DeepSeek V4 Pro left preview — and raised prices", c: "API is $1.32 / $3.96 per 1M tokens as of Aug 16, a 3.6x jump. Artificial Analysis: only one point above V4 Flash." },
        { t: "GPT-5.6-Cyber found two Chrome zero-days", c: "Chained V8 bugs, now CVE-2026-15903. Completes 95% of advanced exploit prompts; GPT-5.6 Sol completes 1.5%." },
        { t: "Claude is watermarking its text", c: "Models launched after Aug 2 use SynthID. Light edits survive; a full rewrite does not. Code barely marks." },
      ],
      note: "Anything we missed that deserved the top five? That's what the walk to the break is for.",
    },

    /* ---- the break, timed by the slide ---- */
    {
      kind: "break",
      clock: "05:00",
      secs: 300,
      c: "Stretch, refill, introduce yourself to somebody you haven't met. The bar knows when time's up.",
    },

    /* ---- segment two: skills and agents ---- */
    {
      kind: "act",
      n: "02",
      eyebrow: "Segment two",
      title: "Skills and agents",
      art: "mark",
      c: "Google's Agent Development Kit is the heavyweight way: a framework, a config, a cloud deploy — all before the agent says one useful word. Tonight we take the other door.",
    },
    {
      kind: "flow",
      title: "Before the agent speaks",
      steps: [
        { t: "Install", c: "The kit, a language, a project." },
        { t: "Define", c: "The agent, written in code." },
        { t: "Configure", c: "Cloud project, APIs, permissions." },
        { t: "Deploy", c: "Push it somewhere it can run." },
        { t: "Talk", c: "The first useful sentence — after all of that.", lit: true },
      ],
      note: "Google's Agent Development Kit is a real way to build agents. It is also a lot of machinery before the first useful sentence.",
    },
    {
      kind: "split",
      title: "Two ways to get an agent",
      left: {
        h: "The ADK way",
        items: [
          "A framework to install",
          "An agent written in code",
          "A cloud project to configure",
          "A deploy before it speaks",
          "The right tool, later",
        ],
      },
      right: {
        h: "The skill way",
        items: [
          "A markdown file",
          "Instructions in your words",
          "A folder the agent already reads",
          "Running tonight, with one word",
          "The right tool, for this room",
        ],
      },
      note: "If you outgrow a file, ADK is still there. Tonight we stay on the file, because that's the one we can finish in this room.",
    },
    {
      kind: "statement",
      text: "Most people don't need a framework. They need instructions the model can read.",
      note: "That's the whole night, said once. Everything after this is that sentence, built live.",
    },
    {
      kind: "walk",
      title: "What a skill is",
      steps: [
        {
          t: "The repeat",
          c: "you typed it twice",
          d: "The same context paragraph, the same format request, the same correction. If you typed it twice this week, that's the skill.",
        },
        {
          t: "The file",
          c: "written once",
          d: "That explanation, saved as instructions. Not a chat. A file the agent opens before it answers you.",
        },
        {
          t: "The read",
          c: "every new thread",
          d: "You don't paste it. You don't re-explain. A fresh thread already has it, because the file is in the folder it reads.",
        },
        {
          t: "The run",
          c: "one word",
          d: "You type the name of the skill. It does the job. The test of a skill is whether a blank thread can run it.",
        },
      ],
      note: "We don't invent an example for this. Whatever you re-typed this week is the one we use.",
    },
    {
      kind: "act",
      n: "03",
      eyebrow: "The file",
      title: "Markdown",
      c: "A plain text file with light formatting. The format agents read best. A skill is just that file with a bit of frontmatter.",
    },
    {
      kind: "bullets",
      title: "What a markdown file actually is",
      items: [
        { t: "Plain text", c: "A file you can open in Notes, in VS Code, or in the agent itself. No special app." },
        { t: "A few marks", c: "Headings, lists, bold. That's most of what a skill ever needs." },
        { t: "Frontmatter", c: "Two lines at the top, between three dashes: the name, and when to use it. That's how the agent finds it." },
        { t: "No deploy", c: "Save it in the skills folder. The next thread reads it. There is no cloud step." },
      ],
      note: "You can open it in Notes. The agent can open it too. That's the whole appeal.",
    },
    {
      kind: "terminal",
      cwd: "~/.claude/skills/meeting-notes",
      cmd: "cat SKILL.md",
      out: [
        "---",
        "name: meeting-notes",
        "description: Turn a messy call into action items. Use after any meeting.",
        "---",
        "Read the notes. List decisions, owners, and dates. Stop if there are no notes.",
      ],
      title: "That's the whole file",
      c: "A name, a one-line description, then the steps. Headings and lists if they help. No framework, no deploy, no cloud project.",
      note: "The description is how it gets found. \"Helps with meetings\" gets found by nobody. \"Turn a messy call into action items\" does.",
    },
    {
      kind: "act",
      n: "04",
      eyebrow: "The thread",
      title: "Start a thread",
      c: "What separates a thread that produces work from a thread that produces conversation. We start one on screen.",
    },
    {
      kind: "walk",
      title: "What a good thread actually contains",
      steps: [
        {
          t: "Context",
          c: "what already exists",
          d: "What you're working on, who it's for, what already exists. Paste the real thing, not a description of it.",
        },
        {
          t: "Role",
          c: "who it should be",
          d: "Who it should be while it answers. \"Someone who has read our last four emails\" beats \"an expert\".",
        },
        {
          t: "Task",
          c: "one verb",
          d: "One job, stated as a verb. If it has an \"and\" in it, that's two threads.",
        },
        {
          t: "Format",
          c: "the shape you'll use",
          d: "How you want it back — length, structure, the shape you'll actually use.",
        },
        {
          t: "Artifact",
          c: "the file you keep",
          d: "The file you keep. Everything above this step is setup for this one.",
        },
      ],
      note: "We start one on screen from here. Nobody writes this in order the first time — you write the task, get something generic, and add the other four.",
    },
    {
      kind: "split",
      title: "Two ways to use the same box",
      left: {
        h: "Conversation",
        items: [
          "One question at a time",
          "Answers you skim",
          "Starts from zero every time",
          "Output lives in the scrollback",
          "You get faster at typing",
        ],
      },
      right: {
        h: "Work",
        items: [
          "A brief, then a draft",
          "Work you edit and send",
          "Starts from your own material",
          "Output lands in a file",
          "Tomorrow starts where tonight ended",
        ],
      },
      note: "Same box, same model. The difference is whether anything survives the tab closing.",
    },
    {
      kind: "act",
      n: "05",
      eyebrow: "The run",
      title: "Create a skill",
      c: "Take the thing you just explained. Write it down as a skill file. Run it fresh with one word.",
    },
    {
      kind: "terminal",
      cmd: "/skill-writer",
      out: ["what did you type twice this week?", "drafting frontmatter + steps…", "wrote .claude/skills/meeting-notes/SKILL.md"],
      title: "The thing you explained, written down",
      c: "It asks what you keep repeating, takes real examples rather than adjectives, writes the steps as instructions, then we run it in a fresh thread with one word — because a skill that only works in the thread that wrote it isn't a skill.",
      note: "We're doing this from the thread we just ran. Follow along or watch; the file is the point, not the typing speed.",
    },
    {
      kind: "flow",
      title: "Tonight's move",
      steps: [
        { t: "The thread", c: "You explain the job, once, on screen." },
        { t: "The file", c: "That explanation, saved as a skill." },
        { t: "The blank thread", c: "No context, no help, no preamble." },
        { t: "One word", c: "The name of the skill. That's the run.", lit: true },
      ],
      note: "If it only works in the thread that wrote it, it isn't a skill yet. The blank thread is the test.",
    },
    {
      kind: "act",
      n: "06",
      eyebrow: "The loop",
      title: "Iterate",
      c: "A skill is never right the first time. Run it, read what sounded wrong, edit the file, run again.",
    },
    {
      kind: "loop",
      title: "The skill loop",
      label: "compounds",
      steps: [
        { t: "Run it in a fresh thread" },
        { t: "Read what sounded wrong" },
        { t: "Edit the file — not the chat" },
        { t: "Run it again" },
      ],
      note: "The corrections are the skill. If you only fix it in the chat, tomorrow's thread makes the same mistake.",
    },
    {
      kind: "terminal",
      cmd: "/meeting-notes",
      out: ["no extra prompt", "owners were missing — editing SKILL.md", "second run: decisions, owners, dates"],
      title: "One word, then a better file",
      c: "Same skill, blank thread, no help. Whatever you had to add by hand goes into the file. The third run should not need you.",
      note: "A skill is never right the first time. That's not a failure — that's the loop.",
    },
    {
      kind: "statement",
      text: "Edit the file, not the chat.",
      note: "Tomorrow's thread only improves if today's correction landed in the file.",
    },
    {
      kind: "act",
      n: "07",
      eyebrow: "The peek",
      title: "A sneak peek at Grok Bot",
      art: "bolt",
      c: "A bot built with the same pieces the room just used — a skill, a markdown file, an agent. Watch it answer live.",
    },
    {
      kind: "flow",
      title: "The distance is shorter than it looks",
      steps: [
        { t: "Markdown", c: "Instructions, in your words." },
        { t: "Skill", c: "Named, saved, read automatically." },
        { t: "Agent", c: "A model that can use the file." },
        { t: "Bot", c: "The same pieces, answering live.", lit: true },
      ],
      note: "We're going to watch it answer live. If it stumbles, you just learned the loop that fixes it.",
    },
    {
      kind: "statement",
      title: "Grok Bot",
      text: "Watch it answer live.",
      tags: ["A skill", "A markdown file", "An agent"],
      note: "I'm not going to walk the architecture. You already have the pieces.",
    },

    /* ---- close ---- */
    {
      kind: "thanks",
      title: "Dan & Workuity",
      tag: "Platinum sponsor · The venue",
      c: "Workuity Biltmore hosts and sponsors every meetup in this series and the October weekend. Rooms like tonight don't happen without Dan and this community — thank him on your way out.",
      img: "/sponsor-workuity.png",
      imgAlt: "Workuity",
    },
    {
      kind: "thanks",
      title: "AutomationInterns.com",
      tag: "Gold sponsor",
      c: "Affordable AI for everyday business — and the newest name on the Ship AI sponsor wall. Welcome Jon S and the interns.",
      img: "/sponsor-automationinterns.png",
      imgAlt: "AutomationInterns.com",
      color: true,
    },
    {
      kind: "end",
      eyebrow: "Sponsors",
      next: "Your logo belongs on this wall",
      qr: "sponsors",
      qrLabel: "The menu — shipai.club",
      c: "If tonight was useful, this is how it stays free. Every tier is published, every arrangement is negotiable — cash, credits, or hours, at every price point. Talk to Santos before you leave, or scan for the menu.",
    },
    {
      kind: "contact",
      title: "Say hi",
      art: "dome",
      rows: [
        { l: "X", v: "@5antoshernandez", c: "Build in public — arguments welcome.", lit: true },
        { l: "Discord", v: "discord.gg/kZSJMNveYM", c: "Where tonight's links, slides, and skills land." },
        { l: "Work with me", v: "desic.xyz", c: "Want systems like these built and run for you? That's my team." },
      ],
      note: "Everything tonight is open source — the deck, the skills, the template repo. Take it all.",
    },
    { kind: "quote", text: "Demos over memos." },
    {
      kind: "end",
      next: "Daily Driver — Session 02, Workuity Biltmore",
      qr: "day-zero-coworking-with-ai",
      qrLabel: "Session page",
      c: "Tonight you wrote a skill and ran it. Next session those skills get a clock — routines, a live calendar, a weekly report that arrives without you asking.",
    },
  ],

  "coworking-with-ai": [
    { kind: "title", sub: "Routines, artifacts, and work that runs on a schedule" },
    {
      kind: "statement",
      text: "AI that waits to be asked is a tool. AI on a calendar is a coworker.",
      note: "Tonight is the difference between those two, built on screen with your files from session 01.",
    },
    {
      kind: "agenda",
      title: "Tonight",
      items: [
        "What a routine is — skill, trigger, checkpoint",
        "Artifacts versus live artifacts",
        "A four-week content calendar, built on screen",
        "Scheduled tasks, demoed live",
        "The weekly report that runs without you",
        "Outbound, drafted — never sent",
        "The checkpoint rule",
      ],
    },

    {
      kind: "timeline",
      title: "Where we are",
      note: "Four sessions, one business — yours. Every session is free and standalone, each one leaves a folder the next one reads, and catching up late is explicitly allowed.",
    },

    {
      kind: "act",
      n: "01",
      eyebrow: "Act one",
      title: "Artifacts",
      c: "A routine is three things: a skill that knows how, a trigger that fires it, and a checkpoint where you're still in the loop. All three start with something worth reading.",
    },
    {
      kind: "split",
      title: "Dead artifact, live artifact",
      left: {
        h: "Dead",
        items: [
          "Generated once, perfect that day",
          "Regenerated from scratch when stale",
          "Lives in a chat you closed",
          "Nobody adds to it",
          "Rewritten every month",
        ],
      },
      right: {
        h: "Live",
        items: [
          "Generated once, then edited forever",
          "Updated when something changes",
          "Lives in a file in your repo",
          "Every routine reads it",
          "More useful in month three",
        ],
      },
      note: "The tell is simple: if the fix for a stale file is \"regenerate it\", it was never live.",
    },
    {
      kind: "terminal",
      cmd: "/content-calendar",
      out: ["reading the icp-profile skill", "4 weeks, 8 slots — 6 entries, 2 left open", "wrote 02-routines/calendar.md"],
      title: "Four weeks, from what they actually ask",
      c: "Not topics that sound like marketing. The questions your ICP types into a search box, and the ones they ask you on a call — turned into a dated four weeks you can argue with.",
      note: "The moment it exists, add one thing to it by hand. That's the edit that makes it yours instead of output.",
    },

    {
      kind: "act",
      n: "02",
      eyebrow: "Act two",
      title: "Schedules",
      c: "Every assistant worth using now runs work on a clock — tasks in ChatGPT, scheduled tasks in Claude, cron if you'd rather own it. The mechanism is the boring part. The pattern is the same everywhere.",
    },
    {
      kind: "flow",
      title: "What a routine is made of",
      steps: [
        { t: "The schedule", c: "Monday at seven, every week, whether you remembered or not." },
        { t: "The skill", c: "The instructions you already wrote once, run again unchanged." },
        { t: "The draft", c: "It reads your files first, then writes. Same inputs you'd have given it by hand." },
        { t: "The checkpoint", c: "You read it. Genuinely, or not at all.", lit: true },
        { t: "The file", c: "It lands somewhere you'll find it later, not in a chat window you closed." },
      ],
      note: "A checkpoint you never actually read isn't a checkpoint — it's theatre with your name on it. Remove it or mean it.",
    },
    {
      kind: "terminal",
      cmd: "/weekly-report",
      out: ["5 numbers you can actually get", "scheduled: Mondays, 7:00 AM", "first run landed — 168 words"],
      title: "The report that shows up on its own",
      c: "Three to five numbers you can genuinely obtain, under two hundred words, in plain English. It says what moved and what it thinks that means, and it's honest about small numbers instead of dressing them up as percentages.",
      note: "If it hasn't run once, it isn't set up. Watch the first one land before you trust the second.",
    },

    {
      kind: "act",
      n: "03",
      eyebrow: "Act three",
      title: "Outbound, drafted",
      c: "The most useful thing an agent does for outbound is the ninety percent before the send button. The send button stays yours.",
    },
    {
      kind: "matrix",
      title: "Who does what",
      heads: ["The agent", "You"],
      rows: [
        { t: "The list", cells: ["Twenty named accounts, each with a reason", { v: "Cut the ones that don't fit", lit: true }] },
        { t: "The sequence", cells: ["First touch, two follow-ups, a break-up", { v: "Cut anything you wouldn't reply to", lit: true }] },
        { t: "The specifics", cells: ["One line per account that couldn't be in anyone else's", { v: "Check that it's true", lit: true }] },
        { t: "Sending", cells: ["Never", { v: "Every one of them, by hand", lit: true }] },
      ],
      note: "Twenty relevant emails take an afternoon. Five hundred bad ones take an afternoon too, and cost you the domain.",
    },
    {
      kind: "terminal",
      cmd: "/icp-builder  →  /outbound-sequence",
      out: ["20 named accounts, 6 filtered out", "1 touch + 2 follow-ups, drafted", "wrote 02-routines/outbound/ — 0 sent"],
      title: "Drafts, into a folder",
      c: "The ICP profile from session 01 becomes a named list, then a sequence short enough to read on a phone. It writes to a folder and stops there — nothing in this program has your outbox.",
    },
    {
      kind: "loop",
      title: "The week, on rails",
      label: "every week",
      steps: [
        { t: "Monday: the numbers land before you open the laptop" },
        { t: "The calendar says what this week's piece is" },
        { t: "Drafts show up in the folder, in your voice" },
        { t: "You edit, you send, and the calendar gets updated" },
      ],
      note: "None of this is new work. It's the same work, minus the remembering — and the last step is the one that keeps the whole loop honest.",
    },
    { kind: "quote", text: "Proof of work." },
    {
      kind: "end",
      next: "First Deploy — Session 03, Workuity Biltmore",
      qr: "day-zero-first-deploy",
      qrLabel: "Session page",
      c: "Everything so far lives in a chat window and a folder. Next session it gets a URL. Bring Node, a GitHub account and a Vercel account — the setup instructions go out in Discord beforehand, and we do the install together in the room.",
    },
  ],

  "first-deploy": [
    { kind: "title", sub: "A marketing site, built and deployed in one sitting" },
    {
      kind: "statement",
      text: "Everything so far has lived in a chat window. Tonight it gets a URL.",
      note: "Same business, same files, same voice. A stranger can finally read it.",
    },
    {
      kind: "agenda",
      title: "Tonight",
      items: [
        "The chat, in your files",
        "Setup, together — the slowest fifteen minutes we run",
        "Your one-pager becomes the hero",
        "Structure: one CTA, proof over adjectives",
        "Pages at scale, without the spam",
        "The articles get a home",
        "Deploy — a real URL, tonight",
      ],
    },

    {
      kind: "timeline",
      title: "Where we are",
      note: "Four sessions, one business — yours. Every session is free and standalone, each one leaves a folder the next one reads, and catching up late is explicitly allowed.",
    },

    {
      kind: "act",
      n: "01",
      eyebrow: "Act one",
      title: "The chat, in your files",
      c: "Claude Code and Codex are the same model you've been talking to for two sessions. The difference is that they can open your files, run the build, and read the error themselves.",
    },
    {
      kind: "split",
      title: "The jump",
      left: {
        h: "The chat window",
        items: [
          "You paste the code in",
          "You paste the answer back",
          "It can't see the other forty files",
          "Every session starts blank",
          "You are the copy-paste layer",
        ],
      },
      right: {
        h: "The agent in your repo",
        items: [
          "It reads the project itself",
          "It writes the file",
          "It runs the build and sees the error",
          "It remembers what's in here",
          "You review and decide",
        ],
      },
      note: "It's a terminal, which is the part that puts people off. Nothing tonight needs you to memorise a single command.",
    },
    {
      kind: "terminal",
      cwd: "~/",
      cmd: "npm i -g @anthropic-ai/claude-code  &&  claude",
      out: ["node v22 — ok", "logged in", "ready in ~/day-zero"],
      title: "Setup, together",
      c: "The slowest fifteen minutes in the program, and we spend them as a room: Node, an account, an agent that starts, the template cloned. Nobody moves on while the person next to them is still installing.",
      note: "Instructions went out in Discord before tonight, and this session needs a paid plan or an API key — said plainly rather than discovered halfway through. If you did the setup at home, this is your coffee break.",
    },

    {
      kind: "act",
      n: "02",
      eyebrow: "Act two",
      title: "The site",
      c: "Every section has a job. Anything without one gets cut, however nice it looks — and the hero is a test of session 01, not a writing exercise.",
    },
    {
      kind: "flow",
      title: "Top to bottom",
      steps: [
        { t: "Hero", c: "What it is, who it's for, one thing to do next. Your one-pager, unchanged if it was any good.", lit: true },
        { t: "Proof", c: "Immediately after. A number, the product doing the hard case, one sentence a real person said." },
        { t: "How it works", c: "Three steps. If it needs five, the product is explaining itself badly." },
        { t: "The objection", c: "Name what they're worried about before they leave to go worry about it." },
        { t: "One CTA", c: "The same one, repeated. A second call to action is the same as none." },
      ],
      note: "If the positioning doesn't survive contact with the page, the positioning was the problem — not the page.",
    },
    {
      kind: "terminal",
      cmd: "/site-scaffold  →  /landing-copy  →  /og-image",
      out: ["scaffolding app/ …", "hero ← 01-voice/positioning.md", "preview: your-site.vercel.app"],
      title: "Scaffold, then say something",
      c: "Routing, metadata and sections first, because an empty page you can deploy beats a perfect page you can't. Then the copy, pulled from the one-pager you wrote in session 01. Then links that preview properly, which is ten minutes you spend once.",
      note: "Proof over adjectives, all the way down. \"Blazing fast\" is discounted by every stranger who reads it; a number with a method behind it isn't.",
    },

    {
      kind: "act",
      n: "03",
      eyebrow: "Act three",
      title: "Pages at scale",
      c: "One table of real data and one template becomes a page per row. Done carelessly it's spam. Done once, carefully, it's the cheapest traffic you'll ever build.",
    },
    {
      kind: "prism",
      title: "One dataset, many pages",
      note: "The same rows, refracted into whichever shape someone actually searches for. Your ICP file already says what they're looking for — this is that list, turned into pages that answer one query each.",
      channels: ["Comparisons", "Use cases", "Integrations", "Locations"],
      rays: 4,
    },
    {
      kind: "bullets",
      title: "The line between scale and spam",
      items: [
        { t: "The doorway test", c: "Read one generated page out loud. If it's a keyword with a header on it, that's a doorway page — search engines are explicitly built to bin those." },
        { t: "Sample of five", c: "Generate five before you generate five hundred. Five is enough to see whether the template has anything to say." },
        { t: "Templated where the data is real", c: "Rows that genuinely differ get a template. Anything that needs judgement gets written by a human, or doesn't get written." },
      ],
      note: "The test isn't \"would this rank\". It's \"would a person be glad they landed here\".",
    },
    {
      kind: "terminal",
      cmd: "/content-map  →  /programmatic-pages  →  deploy",
      out: ["18 real queries → 12 pages", "generating 5 as a sample…", "deployed — live in 34s"],
      title: "Tonight's run",
      c: "Work backwards from what your ICP types into a search box, generate five pages from real data, read one of them properly, then push. The articles you drafted in session 01 get a home on the same deploy.",
    },
    {
      kind: "bignum",
      label: "Your site",
      v: "Live",
      delta: "tonight",
      c: "Not staged, not on your laptop. A URL you can paste into a message and watch someone open.",
    },
    { kind: "quote", text: "If it ships, it speaks." },
    {
      kind: "end",
      next: "The Night Shift — Session 04, Workuity Biltmore",
      qr: "day-zero-agentic-workflows",
      qrLabel: "Session page",
      c: "The site you just shipped grows a support agent that answers from your own pages, and a workflow that drafts next week's article while you sleep. Same repo, prepared branch, nothing built from scratch.",
    },
  ],

  "agentic-workflows": [
    { kind: "title", sub: "A support agent and a workflow that runs while you sleep" },
    {
      kind: "statement",
      text: "Until tonight, everything waited for you to show up.",
      note: "The skills, the site, the drafts — all of it starts when you open a laptop. Tonight two things stop waiting.",
    },
    {
      kind: "agenda",
      title: "Tonight",
      items: [
        "Agent versus workflow — and when each one is wrong",
        "The handoff: your session 03 repo, on a branch",
        "The support agent, on your own site",
        "Guardrails, written before it goes live",
        "The night shift — pick one workflow",
        "Watch a run, then break one on purpose",
        "What compounds from here",
      ],
    },

    {
      kind: "timeline",
      title: "Where we are",
      note: "Four sessions, one business — yours. Every session is free and standalone, each one leaves a folder the next one reads, and catching up late is explicitly allowed.",
    },

    {
      kind: "act",
      n: "01",
      eyebrow: "Act one",
      title: "Agent vs workflow",
      c: "Two different shapes with two different failure modes. Naming which one you're building decides how you test it.",
    },
    {
      kind: "matrix",
      title: "Two shapes",
      heads: ["Agent", "Workflow"],
      rows: [
        { t: "Trigger", cells: ["Someone asks", "The clock"] },
        { t: "Shape", cells: ["A conversation, one turn at a time", "Fixed steps, start to finish"] },
        { t: "Fails by", cells: ["Answering confidently and wrong", "Failing silently at three in the morning"] },
        { t: "You test it by", cells: ["Asking it ten real questions", "Running it by hand and reading the logs"] },
        { t: "Tonight", cells: [{ v: "Support, on your own site", lit: true }, { v: "Drafts, into a review queue", lit: true }] },
      ],
      note: "Neither of these is smarter than the other. One is a front door and one is a factory.",
    },
    {
      kind: "terminal",
      cwd: "~/day-zero-site",
      cmd: "git fetch  &&  git switch night-shift",
      out: ["app/api/chat/route.ts — new", "workflows/weekly.ts — new", "3 packages added"],
      title: "The handoff",
      c: "Tonight extends the exact repo you shipped in session 03 — no fresh codebase, no second setup night. The branch brings an empty chat route and an empty workflow. You write what goes in them; the plumbing is already wired.",
      note: "The branch is pre-tested. If yours doesn't start, we fix it in the room rather than at the end.",
    },

    {
      kind: "act",
      n: "02",
      eyebrow: "Act two",
      title: "The support agent",
      c: "A chat box on your site that answers from your own content, and knows the difference between a question it can answer and one it shouldn't touch.",
    },
    {
      kind: "flow",
      title: "What happens when a stranger asks",
      steps: [
        { t: "Message", c: "Someone asks something on your site, at whatever hour they're awake." },
        { t: "Classify", c: "Is this in your content, out of scope, or something only a human should touch?" },
        { t: "Answer", c: "From your own pages, with the page it came from attached." },
        { t: "Escalate", c: "\"I don't know — here's a human.\" A valid outcome, and the one that keeps it honest.", lit: true },
        { t: "Refuse", c: "Price negotiations, promises, anything with your signature on it. Once, politely, without arguing." },
        { t: "Log", c: "Every conversation written down. Next month's FAQ is already in there." },
      ],
      note: "Answer, escalate, refuse — three legal outcomes and no fourth. An agent with no way to fail will invent one.",
    },
    {
      kind: "bullets",
      title: "Guardrails, written first",
      items: [
        { t: "Never promise", c: "No delivery dates, no refunds, no \"we can definitely do that\". An agent that commits on your behalf has written you a contract." },
        { t: "Never negotiate price", c: "It can quote what's published. Anything past that is a human conversation." },
        { t: "Never send email", c: "It drafts and hands over. Same rule as session 02 — sending is yours." },
        { t: "\"I don't know\" is allowed", c: "Written into the prompt as a valid answer, with the human it hands to. Confident and wrong costs more than slow." },
      ],
      note: "This file gets written before you deploy, not after the first screenshot of it going wrong.",
    },
    {
      kind: "terminal",
      cmd: "/support-agent",
      out: ["answers from your pages, not model memory", "3 outcomes: answer · escalate · refuse", "wrote 04-agents/guardrails.md"],
      title: "Build it, then try to break it",
      c: "The prompt is built from the site you already shipped, so it cites your content instead of remembering something plausible about your industry. Then ten real questions — seven it answers, two it hands to a human, one it refuses.",
      note: "If it answers one of the hand-off two, it isn't ready. That's the test, and it takes five minutes.",
    },

    {
      kind: "act",
      n: "03",
      eyebrow: "Act three",
      title: "The night shift",
      c: "One workflow, running on a schedule, doing the part of your week that never needed you. Pick one tonight — the other one is a step in the guide.",
    },
    {
      kind: "loop",
      title: "The article path",
      label: "runs weekly",
      steps: [
        { t: "The calendar names this week's piece" },
        { t: "The agent drafts it in your voice" },
        { t: "Claims come back marked verified or unverified" },
        { t: "It lands in a review queue — never on the site" },
      ],
      note: "Nothing publishes itself. The queue is the checkpoint from session 02, wearing a different hat — and the numbers path is the same loop with your report at the end of it.",
    },
    {
      kind: "terminal",
      cmd: "/scheduled-workflow",
      out: ["manual trigger first — run #1 in 4.2s", "logs read, one failure forced", "cron written to vercel.json — Mondays 13:00 UTC"],
      title: "Manual first, always",
      c: "Run it by hand, read the logs, then turn the schedule on. Then break it on purpose and confirm you hear about it — a cron job that fails silently is worse than no cron job, because you'll trust it for a month.",
    },
    {
      kind: "scorecard",
      title: "What runs without you now",
      rows: [
        { t: "Answers a repeat question", pct: 90, lit: true },
        { t: "Drafts the week's article", pct: 80 },
        { t: "Reports the numbers", pct: 80 },
        { t: "Decides what ships", pct: 0 },
      ],
      note: "The agent is everyone's. The two middle rows are a pick-one — you build whichever you chose tonight, and the other is a step in the guide and an evening this week. Four sessions ago this was a blank box in a chat window, and the bottom row is zero on purpose: it's the one you keep.",
    },
    { kind: "quote", text: "Feel the fear and do it anyways." },
    {
      kind: "end",
      next: "Zero to Launch — the ten-week program",
      qr: "day-zero-agentic-workflows",
      qrLabel: "Tonight's kit",
      c: "Day Zero got it running. Zero to Launch is the one that puts customers in front of it — funnel, positioning, distribution, and a hackathon at the end where you ship it in public. Tonight's deck, guide and skill files are on the session page.",
    },
  ],
};
