/* ------------------------------------------------------------------
   Growth Loops — the post-acquisition program, six sessions.

   Every session works on the same live product. The sequence starts by
   making behavior measurable, then improves the customer lifecycle from
   first value through repeat value, retention and re-engagement.
------------------------------------------------------------------ */

export const GROWTH_LOOPS_STEPS = [
  {
    name: "Measure",
    copy: "Name the value event, instrument the journey and build a scorecard that changes what the team does next.",
    range: "Session 01",
  },
  {
    name: "Activate",
    copy: "Shorten the path from signup to first value, then help customers repeat the behavior that predicts they will stay.",
    range: "Sessions 02–03",
  },
  {
    name: "Retain",
    copy: "Read cohorts, find where value decays and separate a product problem from a customer-fit or lifecycle problem.",
    range: "Sessions 04–05",
  },
  {
    name: "Compound",
    copy: "Turn one proven behavior into a measurable loop, run a bounded experiment and decide whether to ship, revise or stop.",
    range: "Session 06",
  },
];

export const GROWTH_LOOPS_SESSIONS = [
  {
    n: "01",
    slug: "measure-what-matters",
    venue: "workuity",
    eventTitle: "Instrument the Journey",
    date: null,
    iso: null,
    title: "Build a product scorecard from behavior you can trust",
    act: "Measure",
    copy: "Choose the customer action that represents value, instrument the path to it and build a scorecard small enough to use every week.",
    take: "An instrumented core journey, a validated event plan and a product scorecard with definitions two people can calculate the same way.",
    lede: "Tonight we put one real user through the product and follow every event into the analytics tool. We inspect the payload, fix missing or duplicate data and build the first scorecard only after the journey is trustworthy.",
    why: "A dashboard cannot rescue vague definitions or broken events. Useful measurement starts with a decision, a value event and data the team can verify.",
    agenda: [
      { t: "Start with the decision", c: "Name the weekly product decision the scorecard must support. If a metric cannot change that decision, it does not make the first version." },
      { t: "Define the value event", c: "Replace generic activity with the customer action that signals a useful outcome. Write who did what, under which conditions and how often it counts." },
      { t: "Outcome, drivers and guardrails", c: "Choose one primary outcome, the two or three behaviors that explain it and a small set of quality guardrails that prevent gaming it." },
      { t: "Design the event taxonomy", c: "Events, users, accounts and properties; naming conventions, identity rules and the minimum context required to segment behavior later." },
      { t: "Instrument and validate", c: "Trigger the core journey in the product, inspect the payload, find the user in analytics and check that duplicate or missing events cannot distort the result." },
      { t: "Build the first scorecard", c: "One page with definitions, owners, cadence and links from each number back to the underlying behavior." },
    ],
    bring: "A laptop, access to a product you can instrument and an analytics account. Existing data is useful but not required; a sample product and event stream will be available for anyone starting fresh.",
    commit: "01-measurement/ — metric tree, event taxonomy, validation log and the first product scorecard.",
    skills: [],
  },
  {
    n: "02",
    slug: "activation",
    venue: "workuity",
    eventTitle: "First Value",
    date: null,
    iso: null,
    title: "Find activation and remove one barrier to it",
    act: "Activate",
    copy: "Find the early behavior most connected to later retention, measure the path to it and ship one change that helps new customers reach value sooner.",
    take: "A behavior-based activation definition, a segmented baseline funnel and one shipped onboarding change with its success metric and guardrail.",
    lede: "Tonight we compare what retained customers did early, choose a useful activation signal and walk the signup-to-value path in the product. Then we remove one credible point of friction and define how we will judge the change.",
    why: "Finishing onboarding is not the same as receiving value. Activation matters when an early action connects to the reason a customer should return.",
    agenda: [
      { t: "Activation is a prediction", c: "Define the early behavior that should make retention more likely and the later outcome it is expected to predict." },
      { t: "Find the candidate moments", c: "Compare activated and retained cohorts across first-session behaviors instead of choosing an aha moment by intuition alone." },
      { t: "Map the path to value", c: "Build the signup-to-value funnel, include elapsed time and segment it by source, persona, device or account type." },
      { t: "Read friction honestly", c: "Separate avoidable product friction from qualification, setup that creates real value and customers who were never a fit." },
      { t: "Ship one activation change", c: "Improve sequencing, defaults, empty states or guidance at the highest-leverage step without rebuilding the whole onboarding flow." },
      { t: "Measure the change", c: "Write the success metric, guardrail and observation window before looking at the result." },
    ],
    bring: "A laptop, the measurement plan from session one and access to the product's onboarding flow. A sample funnel will be provided if your product does not have enough users yet.",
    commit: "02-activation/ — activation definition, segmented funnel, friction notes, shipped change and experiment readout template.",
    skills: [],
  },
  {
    n: "03",
    slug: "engagement",
    venue: "workuity",
    eventTitle: "Repeat Value",
    date: null,
    iso: null,
    title: "Build the next useful action into the product",
    act: "Activate",
    copy: "Define healthy engagement for this product, find what retained customers repeat and make the next valuable action easier to discover.",
    take: "A product-specific active-use definition, a feature-adoption view and one in-product or lifecycle intervention tied to repeat value.",
    lede: "Tonight we define the product's natural usage rhythm, compare the behaviors of retained and slipping customers and build one path back to the core action. We measure the value created—and the annoyance or friction the intervention could add.",
    why: "More clicks, sessions or time spent do not automatically mean a healthier product. Engagement is useful only when it describes value a customer has reason to repeat.",
    agenda: [
      { t: "Define an active customer", c: "Choose the behavior and time window that match the product's natural usage frequency rather than defaulting to DAU or MAU." },
      { t: "Frequency, depth and breadth", c: "Decide which dimensions signal value for this product and which are vanity or even signs of friction." },
      { t: "Find the retained behavior", c: "Compare feature adoption and action sequences for retained and slipping cohorts without confusing correlation for causation." },
      { t: "Build the engagement view", c: "Track the core action, supporting feature adoption and the segment that should reasonably perform each behavior." },
      { t: "Design the next-value path", c: "Use empty states, progress, templates, collaboration or triggered guidance to make the next useful action obvious." },
      { t: "Add a trust guardrail", c: "Measure dismissals, errors, unwanted notifications or other costs that could make the engagement number rise while the experience gets worse." },
    ],
    bring: "A laptop, the instrumented product and access to product analytics or the supplied dataset. Bring one feature you believe should drive repeat use.",
    commit: "03-engagement/ — active-use definition, adoption view, retained-behavior analysis and the next-value intervention.",
    skills: [],
  },
  {
    n: "04",
    slug: "retention",
    venue: "workuity",
    eventTitle: "Read the Curve",
    date: null,
    iso: null,
    title: "Use cohorts to find where repeat value holds—or fades",
    act: "Retain",
    copy: "Choose the right retention definition, read the cohort curve and find the customer segment and behavior most worth learning from.",
    take: "A product-appropriate retention metric, a segmented cohort analysis and a ranked set of hypotheses tied to observable behavior.",
    lede: "Tonight we build the retention view, follow cohorts across time and find where repeat use starts to hold or fall away. Then we connect the pattern to customer feedback and choose the strongest hypothesis to investigate.",
    why: "Top-line averages hide when customers started, what they experienced and who is actually staying. Cohorts expose those differences without pretending the chart explains the cause.",
    agenda: [
      { t: "Choose the retention definition", c: "N-day, rolling or bracket retention; behavioral or revenue retention; select the definition and interval that match how value recurs." },
      { t: "Read the cohort table", c: "Follow one cohort across time, distinguish age from calendar effects and recognize what a flattening—or falling—curve can and cannot prove." },
      { t: "Segment for a reason", c: "Compare persona, plan, acquisition source and activation behavior only where the result could change the product decision." },
      { t: "Find the bright spots", c: "Locate the customers already retaining, then identify the jobs, setup and repeated behaviors that distinguish them." },
      { t: "Locate value decay", c: "Find the interval and journey state where use drops, then connect the quantitative pattern to support, interview or cancellation evidence." },
      { t: "Rank the hypotheses", c: "Score opportunities by expected effect, evidence, effort and guardrail risk; choose one to carry into the next session." },
    ],
    bring: "A laptop and enough event history to cover at least two natural product cycles, or the supplied cohort dataset. Bring customer feedback if you have it; behavior shows where, not always why.",
    commit: "04-retention/ — retention definition, cohort views, segment comparison and ranked retention hypotheses.",
    skills: [],
  },
  {
    n: "05",
    slug: "churn-and-reengagement",
    venue: "workuity",
    eventTitle: "Before They Leave",
    date: null,
    iso: null,
    title: "Spot churn earlier and earn a useful return",
    act: "Retain",
    copy: "Define churn for the product, identify the behavior that precedes it and build one intervention around unfinished customer value—not a generic win-back blast.",
    take: "A precise churn definition, an actionable at-risk cohort and a behavior-triggered re-engagement flow measured against a holdout.",
    lede: "Tonight we work backward from churn, compare customers who stayed with those who left and build a segment the product team can act on. Then we trigger one useful intervention and measure whether returning customers reach value again.",
    why: "Cancellation, failed payment, poor fit and fading use are different problems. Treating them as one campaign wastes attention, hides the real cause and can damage trust.",
    agenda: [
      { t: "Define churn and its denominator", c: "Logo, user, activity or revenue churn; voluntary and involuntary; write the boundary and time window before calculating the rate." },
      { t: "Separate the causes", c: "Distinguish failure to activate, value decay, customer-fit, service, price and payment problems using behavior plus qualitative evidence." },
      { t: "Find the leading signals", c: "Compare retained and churned journeys to identify meaningful drops in frequency, feature use, collaboration or successful outcomes." },
      { t: "Build the at-risk cohort", c: "Create a segment with an explicit entry rule, exit rule and reason the team can act on." },
      { t: "Design re-engagement around value", c: "Choose the right surface and message to help the customer resume a useful job; suppress people for whom outreach would be irrelevant or harmful." },
      { t: "Measure return that lasts", c: "Track reactivation, repeat value after return, incremental lift against a holdout and unsubscribe or complaint guardrails." },
    ],
    bring: "A laptop, retention analysis and access to lifecycle messaging or the supplied workflow. Cancellation reasons, failed-payment states and support themes are useful inputs if available.",
    commit: "05-reengagement/ — churn definition, risk cohort, intervention flow, suppression rules and incremental-lift scorecard.",
    skills: [],
  },
  {
    n: "06",
    slug: "compound-the-loop",
    venue: "workuity",
    eventTitle: "Close the Loop",
    date: null,
    iso: null,
    title: "Ship one measurable product growth loop",
    act: "Compound",
    copy: "Turn one proven customer behavior into a loop with a measurable input, output and cycle time. Ship the smallest experiment that can prove whether the mechanism works.",
    take: "A working loop prototype, an instrumented experiment and a 30-day cadence for deciding what to ship, revise or stop.",
    lede: "The final night connects the whole program. We choose one behavior that already creates value, map how its output can produce the next input and launch a bounded experiment. Then we inspect the events and make the decision from evidence.",
    why: "Drawing a circle around a funnel does not make it compound. A real loop produces an output that feeds another turn, at a rate and speed the team can observe.",
    agenda: [
      { t: "Name the loop mechanism", c: "Retention, collaboration, content, data or another product-specific loop; identify why completing the core action can create a future input." },
      { t: "Model one turn", c: "Write the input, conversion steps, value exchange, output, cycle time and point where the output re-enters the system." },
      { t: "Find the constraint", c: "Use the prior five sessions to identify the weakest conversion or slowest cycle instead of optimizing every stage at once." },
      { t: "Write the experiment contract", c: "One hypothesis, primary metric, diagnostic drivers, guardrails, audience, observation window and decision rule before launch." },
      { t: "Ship and inspect", c: "Launch the smallest loop intervention, verify every event and walk through the customer experience end to end." },
      { t: "Decide from the evidence", c: "Present the result and choose ship, revise or stop. Leave with an owner and weekly cadence, not a dashboard nobody opens." },
    ],
    bring: "A laptop, the product, the five prior session artifacts and permission to ship a bounded experiment. A sample product is available for anyone attending without a live user base.",
    commit: "06-growth-loop/ — loop model, working intervention, event validation, experiment readout and 30-day operating cadence.",
    skills: [],
  },
].sort((a, b) => a.n.localeCompare(b.n));
