/* ------------------------------------------------------------------
   The First Build — three workshops and a capstone hackathon.

   The curriculum expands workshop-01.md into a sequence where every
   session adds a working layer to the same product. Dates intentionally
   remain unset until the next cohort is scheduled.
------------------------------------------------------------------ */

export const PRODUCT_BUILDER_STEPS = [
  {
    name: "Frame",
    copy: "Learn the builder's mental model, turn an idea into a precise brief, and use Git as the safety net for fast AI-assisted work.",
    range: "Session 01",
  },
  {
    name: "Build",
    copy: "Connect the interface, API and database, secure the seams, and put the first useful version online.",
    range: "Session 02",
  },
  {
    name: "Engineer",
    copy: "Move from prompting for snippets to directing an agent that plans, tests, debugs and verifies a complete feature.",
    range: "Session 03",
  },
  {
    name: "Ship",
    copy: "A capstone hackathon: build one focused product, prove the core path works and demo a live URL to the room.",
    range: "Session 04 · Hackathon",
  },
];

export const PRODUCT_BUILDER_SESSIONS = [
  {
    n: "01",
    slug: "vibe-coding-foundations",
    venue: "workuity",
    eventTitle: "From Idea to Build Plan",
    date: null,
    iso: null,
    title: "Vibe coding, prompting, Git and the fundamentals that keep you moving",
    act: "Frame",
    copy: "Start with the shift from autocomplete to agentic engineering, then learn where vibe coding works, where it breaks and how to describe a product clearly enough for an AI to build with you. Git, the terminal and project structure are taught through the product in front of you, so you can see what changed and recover when a build goes sideways.",
    take: "A scoped product brief, a working project on your laptop, its first clean checkpoint pushed to GitHub and a repeatable prompt pattern for turning intent into small, reviewable changes.",
    lede: "The first night gives you enough technical footing to build quickly without treating the codebase like a black box. We take one product idea from a vague sentence to a useful brief, scaffold it with an AI coding tool, and save the first clean checkpoint in Git.",
    why: "AI makes clear thinking more valuable, not less. Without a specific outcome, constraints and a safe way back, faster generation only creates a faster mess. This session installs the habits that make every later build recoverable.",
    agenda: [
      { t: "Vibe coding to agentic engineering", c: "The four waves of AI-assisted development, where vibe coding works and breaks, and why building a screen is different from building a system." },
      { t: "Prompt for outcomes", c: "Turn a vague request into what, where, behavior, constraints and a definition of done — enough context to get a useful first pass." },
      { t: "Read the shape of an app", c: "Files, components, routes, packages and the terminal explained through the project in front of you." },
      { t: "Git as your safety net", c: "Clone, branch, commit, inspect a diff and recover from a bad turn before the stakes get higher." },
      { t: "Generate and review the first slice", c: "Ask the agent to plan and generate one visible interface, run it in the browser, inspect the diff and undo one bad change before saving the clean version." },
      { t: "Secrets and safe defaults", c: "Environment variables, .gitignore and the difference between browser-safe configuration and server-only keys." },
    ],
    bring: "A laptop, a GitHub account and access to an AI coding tool such as Codex or Claude Code. No professional coding experience is required, but you should be comfortable using a laptop and completing the setup steps shared before the session. Watching and pairing are welcome.",
    commit: "01-foundations/ — product brief, project map, prompt recipe and the URL of your first GitHub repository.",
    skills: [],
  },
  {
    n: "02",
    slug: "full-stack-building-blocks",
    venue: "workuity",
    eventTitle: "Make It Real",
    date: null,
    iso: null,
    title: "Interfaces, APIs, databases, security and deployment",
    act: "Build",
    copy: "Follow one piece of data all the way through a real product: from a form in the browser, through an API, into a database and back onto the screen. Secure that path, then deploy it through a repeatable push-to-production workflow. If time allows, connect a supplied automation as an extension.",
    take: "A deployed full-stack product with a form-to-API-to-database path you can explain, inspect, secure and debug.",
    lede: "This is the night the boxes connect. Instead of memorizing definitions, you submit real data, watch the network request, inspect the database row and debug the failure points with the agent beside you.",
    why: "Most vibe-coded products break at the seams: the interface looks finished, but the API, data model or deployment assumptions do not hold. Knowing how information travels through the system lets you ask better questions and recognize when the answer is wrong.",
    agenda: [
      { t: "The browser and the server", c: "What belongs in each place, how a request crosses the boundary and why secret keys never belong in frontend code." },
      { t: "APIs and JSON by watching one", c: "Read the method, URL, headers, body, JSON response and status code in the browser's network panel instead of memorizing an abstract diagram." },
      { t: "CRUD and a database that matches the product", c: "Tables, rows, IDs and relationships; design the smallest useful schema, then create, read, update and delete a record through the app." },
      { t: "Connect and inspect the full path", c: "Submit the form, watch the request, inspect the saved row and render it back in the interface with loading, empty, success and error states." },
      { t: "Secure the seams", c: "Keep keys server-side, validate input on the server, enable database access rules, verify webhook signatures and run a short pre-ship security checklist." },
      { t: "CI/CD, deploy and debug", c: "Push the repository, let automated checks gate the deploy, set environment variables and fix the first production-only error from its logs. A supplied automation is the optional extension." },
    ],
    bring: "A laptop and the repository from session one. You will need accounts for GitHub and the selected hosting and database services. The setup guide will name those services, any free-tier limits and any expected usage costs before the session.",
    commit: "02-full-stack/ — live URL, data-flow diagram, schema notes, security checklist and evidence of one successful push-to-deploy run.",
    skills: [],
  },
  {
    n: "03",
    slug: "agentic-engineering",
    venue: "workuity",
    eventTitle: "Direct the Agent",
    date: null,
    iso: null,
    title: "Plan a feature, give the agent context, test it and verify the result",
    act: "Engineer",
    copy: "Graduate from asking for code snippets to directing a complete, reviewable feature. Give the agent durable context, have it plan across the codebase, run tests and use browser, terminal and data tools while you review the evidence and hold the product decisions.",
    take: "A tested feature delivered through a reusable plan-execute-observe-iterate workflow, plus project instructions your next agent session can trust.",
    lede: "Session three moves beyond one-shot code generation. You define the outcome and evidence, the agent reads the repository and proposes a plan, then it implements, runs checks and proposes fixes while you review the result and hold the product decisions.",
    why: "Agentic engineering works when the agent can see the system, use tools and recognize done. Tests, logs and explicit acceptance criteria turn the loop from 'looks right' into evidence you can inspect.",
    agenda: [
      { t: "The agentic loop", c: "Plan, execute, observe and iterate — what the agent owns, what the human owns and when to interrupt." },
      { t: "Give the repository memory", c: "Write project instructions, reusable skills, conventions and commands once so future sessions start with the right context." },
      { t: "Scope a feature", c: "Acceptance criteria, edge cases and a short implementation plan that can survive contact with the existing codebase." },
      { t: "Tests as the specification", c: "Types, lint, build checks, unit tests and browser tests; make one check fail, read the output, fix it and rerun the gauntlet." },
      { t: "Verify the outcome, not just the code", c: "Use browser and integration tools to complete the user journey, visually inspect the interface and query the resulting database row and defaults." },
      { t: "Let failure steer the work", c: "Read terminal output and server logs, have the agent diagnose the evidence and propose a fix, then verify the result instead of guessing." },
      { t: "Review before you ship", c: "Inspect the diff for security, unintended scope and user-facing regressions, then leave a clean checkpoint." },
    ],
    bring: "A laptop and your deployed project from session two. Bring access to its repository, database and deployment logs so the agent can work across the whole loop.",
    commit: "03-agentic/ — feature brief, agent plan, tests, verification log and the final reviewed diff.",
    skills: [],
  },
  {
    n: "04",
    slug: "first-build-hackathon",
    venue: "workuity",
    eventTitle: "The First Build Hackathon",
    date: null,
    iso: null,
    title: "Build, verify and demo one useful product",
    act: "Ship",
    audience: "Capstone",
    copy: "Put the whole stack together in a focused build sprint. Start with a one-page brief, work in small agentic loops, test the core journey and finish with a live product demo — not a slide deck.",
    take: "A focused product or reviewable build, evidence that the core user journey works and a short live-demo format you can reuse.",
    lede: "The final session is a hackathon built for completion. Solo builders and small teams choose one narrow problem, define the finish line before coding, then use mentors and AI agents to get a working product across it. The room ends with live demos and honest build notes.",
    why: "The concepts only become durable when you use them under a deadline. A constrained capstone forces the decisions real product work requires: what not to build, what must be tested and what evidence makes a demo credible.",
    agenda: [
      { t: "Brief and team formation", c: "Choose one user, one painful job and one core journey. Lock the definition of done before the first agent starts." },
      { t: "Architecture check", c: "Sketch the interface, data and integrations; identify secrets, external dependencies and the riskiest assumption." },
      { t: "Build in vertical slices", c: "Ship the smallest end-to-end path first, commit it, then add only what strengthens the core outcome." },
      { t: "Mentor and verification rounds", c: "Get product and engineering feedback, run the checks that match your risk, and test the app as a stranger would." },
      { t: "Deploy freeze", c: "Put the final build online, capture the repository state and stop adding features while there is still time to fix the demo path." },
      { t: "Live demos", c: "Show the problem, perform the core journey on the live product and share one thing the agent got wrong that you caught." },
    ],
    bring: "A laptop, your repository and an idea you can explain in two sentences. Teams can form at the event; existing products are welcome if the capstone adds and verifies a meaningful new workflow.",
    commit: "04-hackathon/ — live URL, final brief, verification evidence, demo notes and a short retrospective.",
    skills: [],
  },
].sort((a, b) => a.n.localeCompare(b.n));
